user_name: "hadoop"
user_password: "hadoop"

fqnd_cluster: "hadoop"
ip_internal_master: "127.0.0.1"

hadoop_base: "/opt"

hadoop_home: "{{hadoop_base}}/hadoop-3.3.0"

mirror_url_ftp: "http://ftp.unicamp.br/pub/apache/hadoop/common/hadoop-3.3.0/hadoop-3.3.0.tar.gz"
java_home: "/usr/lib/jvm/java-1.8.0-openjdk-amd64"

ip_slaves: "127.0.0.1"
ip_master: "127.0.0.1"

hdfs_replication: 1
path_dfs: "/dfs"

list_users: ["hadoop", "gce"]

hadoop_log_dir: "/var/log/hadoop/"